#### Naveen Kusakula - B00781205
#### Theja Manasa Thatiparti - B00813459

### Q1. Collocation extraction . ( 35 marks )
> a. Tokenize this corpus and perform part-of-speech tagging on it. ( 5 marks )

>import dataset fetch_20newsgroups from Scikit learn

In [10]:
from sklearn.datasets import fetch_20newsgroups

In [11]:
import os, ssl
if (not os.environ.get('PYTHONHTTPSVERIFY', '') and
    getattr(ssl, '_create_unverified_context', None)): 
    ssl._create_default_https_context = ssl._create_unverified_context

>* Area of interest for this assignment is below four newsgroups 
>* *Shuffle* and *random_state* are used to increase the randomness in the dataset which will be useful while training and splitting the dataset

In [12]:
interest = ['alt.atheism', 'talk.religion.misc','comp.graphics','sci.space',]
newsgroups_train = fetch_20newsgroups(subset='train',categories=interest,shuffle=True, random_state=42)

> Displaying sample data element stored in array of arrays

In [13]:
print(newsgroups_train.data[0])

From: rych@festival.ed.ac.uk (R Hawkes)
Subject: 3DS: Where did all the texture rules go?
Lines: 21

Hi,

I've noticed that if you only save a model (with all your mapping planes
positioned carefully) to a .3DS file that when you reload it after restarting
3DS, they are given a default position and orientation.  But if you save
to a .PRJ file their positions/orientation are preserved.  Does anyone
know why this information is not stored in the .3DS file?  Nothing is
explicitly said in the manual about saving texture rules in the .PRJ file. 
I'd like to be able to read the texture rule information, does anyone have 
the format for the .PRJ file?

Is the .CEL file format available from somewhere?

Rych

Rycharde Hawkes				email: rych@festival.ed.ac.uk
Virtual Environment Laboratory
Dept. of Psychology			Tel  : +44 31 650 3426
Univ. of Edinburgh			Fax  : +44 31 667 0150



#### Tokenization and Parts of speech tagging for uncleaned corpus

> Ref: https://www.datacamp.com/community/tutorials/text-analytics-beginners-nltk

> * import nltk,pandas libraries
* *word_tokenize*  tokenizes this dataset into array of arrays of word strings
* As we have array of arrays we used for loop with iteration continued till the length of the dataset and appended each array of tokens to get  result containing a single array of tokens.
* This process will be helpful **to calculate and compare the frequency of words in the entire corpus**, which is meaningful compared to the frequency results within only a part of dataset

In [14]:
import nltk
nltk.download('all')
import pandas as pd
from nltk import pos_tag
from nltk.tokenize import word_tokenize

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     /Users/naveenkusakula/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     /Users/naveenkusakula/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /Users/naveenkusakula/nltk_data...
[nltk_data]    |   Package biocreative_ppi is already up-to-date!
[nltk_data]    | Downloading package brown to
[nltk_data]    |     /Users/naveenkusakula/nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to
[nltk_data]    |     /Users/naveenkusakula/nltk_data...
[nltk_data]    |   Package brown_tei is already up-to-date!
[nltk_data]    | Downloading package cess_cat to
[nltk_data]    |     /Users/naveenkusakula/nltk_data...
[nltk_data]    |   P

In [15]:
#Tokenizing the words
words=[]
for i in range(len(newsgroups_train.data)):
        document = newsgroups_train.data[i]
        words += word_tokenize(document)


In [16]:
#POS tagging the words
print("Number of words after Tokenization:") 
print(len(words))
print("Sample words after Tokenization:")
print(words[:30])
print("Sample words after POS tagging:")
nltk.pos_tag(words)

Number of words after Tokenization:
788086
Sample words after Tokenization:
['From', ':', 'rych', '@', 'festival.ed.ac.uk', '(', 'R', 'Hawkes', ')', 'Subject', ':', '3DS', ':', 'Where', 'did', 'all', 'the', 'texture', 'rules', 'go', '?', 'Lines', ':', '21', 'Hi', ',', 'I', "'ve", 'noticed', 'that']
Sample words after POS tagging:


[('From', 'IN'),
 (':', ':'),
 ('rych', 'NN'),
 ('@', 'NN'),
 ('festival.ed.ac.uk', 'NN'),
 ('(', '('),
 ('R', 'NNP'),
 ('Hawkes', 'NNP'),
 (')', ')'),
 ('Subject', 'NN'),
 (':', ':'),
 ('3DS', 'CD'),
 (':', ':'),
 ('Where', 'WRB'),
 ('did', 'VBD'),
 ('all', 'PDT'),
 ('the', 'DT'),
 ('texture', 'NN'),
 ('rules', 'NNS'),
 ('go', 'VB'),
 ('?', '.'),
 ('Lines', 'NNS'),
 (':', ':'),
 ('21', 'CD'),
 ('Hi', 'NNP'),
 (',', ','),
 ('I', 'PRP'),
 ("'ve", 'VBP'),
 ('noticed', 'VBN'),
 ('that', 'IN'),
 ('if', 'IN'),
 ('you', 'PRP'),
 ('only', 'RB'),
 ('save', 'VB'),
 ('a', 'DT'),
 ('model', 'NN'),
 ('(', '('),
 ('with', 'IN'),
 ('all', 'DT'),
 ('your', 'PRP$'),
 ('mapping', 'NN'),
 ('planes', 'NNS'),
 ('positioned', 'VBN'),
 ('carefully', 'RB'),
 (')', ')'),
 ('to', 'TO'),
 ('a', 'DT'),
 ('.3DS', 'NN'),
 ('file', 'NN'),
 ('that', 'IN'),
 ('when', 'WRB'),
 ('you', 'PRP'),
 ('reload', 'VBP'),
 ('it', 'PRP'),
 ('after', 'IN'),
 ('restarting', 'VBG'),
 ('3DS', 'CD'),
 (',', ','),
 ('they', 'PRP'),
 (

#### Frequency with Filter, PMI, T-test, Chi-Sq test
> b. Apply the techniques described in Tutorial 6 (Frequency with filter, PMI, T-test with filter,
Chi-Sq test) to extract bigram collocations from the corpus. Show the top 20 results of each
technique. (15 marks)

Frequency without filter
> *  compare pairs of words (bigram where n=2 of n-grams)to see which pair is more likely to occur in the dataset -frequency
* Frequency is calculated first without applying any filter or cleaning of dataset (ie.. with stopwords)

In [17]:
#Frequency without filter
from nltk.collocations import *
bigramFinder = BigramCollocationFinder.from_words(words) # collocation identification
bigram_freq = bigramFinder.ngram_fd.items()
bigramFreqTable = pd.DataFrame(list(bigram_freq), columns=['bigram','freq']).sort_values(by='freq', ascending=False)

print("Top 20 bigrams as per frequencies without filter:")
bigramFreqTable[:20]

Top 20 bigrams as per frequencies without filter:


bigram   freq
1132           (--, --)  12597
2107             (>, >)   5806
534           (of, the)   3084
568            (,, and)   2619
0             (From, :)   2136
9          (Subject, :)   2085
271              (., >)   2051
21           (Lines, :)   2049
4250             (|, >)   1979
180   (Organization, :)   1950
1284           (., The)   1745
8          (), Subject)   1742
87            (in, the)   1738
102              (., I)   1734
202              (:, >)   1689
159             (Re, :)   1599
201         (writes, :)   1544
1324           (,, but)   1489
158             (:, Re)   1462
200         (), writes)   1310

Frequency with filter
> * Frequency calculated by removing stopwords in bigrams to get better result 
* Frequency calculated for only (Noun,Noun) and (Adjective,Noun)

In [18]:
#Frequency with filter
from nltk.corpus import stopwords
#get english stopwords
en_stopwords = set(stopwords.words('english'))

#function to filter out for ADJ/NN bigrams
def rightTypes(ngram):
    if '-pron-' in ngram or '' in ngram or ' 'in ngram or 't' in ngram:
        return False
    for word in ngram:
        if word in en_stopwords:
            return False
    acceptable_types = ('JJ', 'JJR', 'JJS', 'NN', 'NNS', 'NNP', 'NNPS')
    second_type = ('NN', 'NNS', 'NNP', 'NNPS')
    tags = nltk.pos_tag(ngram)
    if tags[0][1] in acceptable_types and tags[1][1] in second_type:
        return True
    else:
        return False

In [19]:
#filtered bigrams
filtered_bi = bigramFreqTable[bigramFreqTable.bigram.map(lambda x: rightTypes(x))]
print("Top 20 bigrams as per frequencies with filter:")
filtered_bi[:20]

Top 20 bigrams as per frequencies with filter:


bigram  freq
2107                       (>, >)  5806
4250                       (|, >)  1979
190                  (article, <)  1126
4264                       (>, |)   685
1438                       (|, |)   554
2658                       (>, <)   137
12423                      (*, *)   128
1726   (world, NNTP-Posting-Host)   128
6593        (@, newton.apple.com)   126
6592                 (sandvik, @)   126
9533                       (], >)   124
1454         (@, zoo.toronto.edu)   117
8049         (@, cco.caltech.edu)   112
709         (@, access.digex.com)   104
1457             (Henry, Spencer)    96
9225              (@, netcom.com)    96
12479                     (ra, >)    95
8048                   (keith, @)    95
8029               (Jon, Livesey)    93
8025                 (livesey, @)    92

PMI (Pointwise Mutual Information)

> * Removed the bigrams with frequency less than 20 as they are not useful for analysis using *apply_freq_filter*

In [20]:
#PMI
bigram_measures = nltk.collocations.BigramAssocMeasures()
#removes the bigrams which has frequency less than 20 as they are not useful for analysis
bigramFinder.apply_freq_filter(20) 
bigramPMITable = pd.DataFrame(list(bigramFinder.score_ngrams(bigram_measures.pmi)), columns=['bigram','PMI']).sort_values(by='PMI', ascending=False)
print("Top 20 bigrams as per PMI:")
bigramPMITable[:20]

Top 20 bigrams as per PMI:


bigram        PMI
0          (comme, aucun)  15.266065
1       (525-3684, Telos)  15.195676
2    (Steinn, Sigurdsson)  15.195676
3          (ISLAMIC, LAW)  15.128562
4         (M/S, 525-3684)  15.064432
5           (fait, comme)  15.064432
6       (sank, Manhattan)  14.997317
7      (Carnegie, Mellon)  14.833106
8          (Beam, Jockey)  14.730013
9         (Bake, Timmons)  14.707575
10    (Frequently, Asked)  14.630477
11         (Chapel, Hill)  14.619702
12       (Brigham, Young)  14.479469
13         (Los, Angeles)  14.418069
14            (MY, REPLY)  14.394580
15  (Cookamunga, Tourist)  14.378540
16    (Resource, Listing)  14.370763
17              (fred, j)  14.318533
18     (Asked, Questions)  14.266065
19               (et, al)  14.238461

T-test with filter

> * Applied  filter (rightTypes function) as done above in "frequency with filter" to remove stopwords in bigrams

In [21]:
# T-test with filter
bigramTtable = pd.DataFrame(list(bigramFinder.score_ngrams(bigram_measures.student_t)), columns=['bigram','t']).sort_values(by='t', ascending=False)
# Applying same filter (rightTypes function) as done above in "frequency with filter" to remove stopwords in bigrams
filteredT_bi = bigramTtable[bigramTtable.bigram.map(lambda x: rightTypes(x))]
print("Top 20 bigrams as per T-test:")
filteredT_bi[:20]

Top 20 bigrams as per T-test:


bigram          t
1                        (>, >)  67.793577
8                        (|, >)  41.903078
19                 (article, <)  33.448606
34                       (|, |)  22.661219
38                       (>, |)  21.782338
203  (world, NNTP-Posting-Host)  11.281066
204                      (*, *)  11.276498
211       (@, newton.apple.com)  11.115683
212                (sandvik, @)  11.115683
225        (@, zoo.toronto.edu)  10.711340
240        (@, cco.caltech.edu)  10.479966
266       (@, access.digex.com)  10.098748
291            (Henry, Spencer)   9.796450
295             (@, netcom.com)   9.702564
298              (Jon, Livesey)   9.642051
304                  (keith, @)   9.590963
317                (livesey, @)   9.493201
319                    (TIN, [)   9.473896
322                     (ra, >)   9.463118
323                  (henry, @)   9.462749

Chi-Sq test

>

In [22]:
#Chi-Sq test
bigramChiTable = pd.DataFrame(list(bigramFinder.score_ngrams(bigram_measures.chi_sq)), columns=['bigram','chi-sq']).sort_values(by='chi-sq', ascending=False)
print("Top 20 bigrams as per Chi-Sq test:")
bigramChiTable.head(20)

Top 20 bigrams as per Chi-Sq test:


bigram         chi-sq
0       (525-3684, Telos)  788086.000000
1      (Carnegie, Mellon)  788086.000000
2   (Cookamunga, Tourist)  788086.000000
3    (Steinn, Sigurdsson)  788086.000000
4          (comme, aucun)  788086.000000
5        (VAX/VMS, VNEWS)  761369.287996
6          (ISLAMIC, LAW)  752262.954520
7           (VNEWS, 1.41)  746604.947174
8          (Los, Angeles)  722409.416552
9         (M/S, 525-3684)  719554.956473
10    (Frequently, Asked)  710180.413690
11         (Beam, Jockey)  706557.172325
12      (sank, Manhattan)  686846.875418
13          (fait, comme)  685289.565151
14     (Allan, Schneider)  658747.051132
15       (Henry, Spencer)  623144.868326
16          (Ron, Baalke)  622671.801378
17      (Tourist, Bureau)  620400.254950
18      (Jet, Propulsion)  608140.330727
19        (Bake, Timmons)  588626.228221

> * Sorting and arranging the index  for frequency with filter and filtered T-test as it is not starting from zero, which thereby avoids inconsistent results while displaying all tables together 

In [23]:
#Reset index of Frequency without filter
#Ref: https://stackoverflow.com/questions/19609631/python-changing-row-index-of-pandas-data-frame
sortedFrequencyWithFilter = filtered_bi[:20]
sortedFrequencyWithFilter.index = range(20) 
sortedFilteredTtest = filteredT_bi[:20]
sortedFilteredTtest.index=range(20)

> Concatenate all tabular results to compare

In [24]:
#Concatenate all tables to compare each other
comp=pd.concat([sortedFrequencyWithFilter['bigram'], bigramPMITable['bigram'],sortedFilteredTtest['bigram'],bigramChiTable['bigram']],axis=1, keys=['filtered_bi', 'bigramPMITable','bigramTtable','bigramChiTable'])
comp.head(20)

filtered_bi         bigramPMITable  \
0                       (>, >)         (comme, aucun)   
1                       (|, >)      (525-3684, Telos)   
2                 (article, <)   (Steinn, Sigurdsson)   
3                       (>, |)         (ISLAMIC, LAW)   
4                       (|, |)        (M/S, 525-3684)   
5                       (>, <)          (fait, comme)   
6                       (*, *)      (sank, Manhattan)   
7   (world, NNTP-Posting-Host)     (Carnegie, Mellon)   
8        (@, newton.apple.com)         (Beam, Jockey)   
9                 (sandvik, @)        (Bake, Timmons)   
10                      (], >)    (Frequently, Asked)   
11        (@, zoo.toronto.edu)         (Chapel, Hill)   
12        (@, cco.caltech.edu)       (Brigham, Young)   
13       (@, access.digex.com)         (Los, Angeles)   
14            (Henry, Spencer)            (MY, REPLY)   
15             (@, netcom.com)  (Cookamunga, Tourist)   
16                     (ra, >)    (Resource, Listing)   
17                  (keith, @)              (fred, j)   
18              (Jon, Livesey)     (Asked, Questions)   
19                (livesey, @)               (et, al)   

                  bigramTtable         bigramChiTable  
0                       (>, >)      (525-3684, Telos)  
1                       (|, >)     (Carnegie, Mellon)  
2                 (article, <)  (Cookamunga, Tourist)  
3                       (|, |)   (Steinn, Sigurdsson)  
4                       (>, |)         (comme, aucun)  
5   (world, NNTP-Posting-Host)       (VAX/VMS, VNEWS)  
6                       (*, *)         (ISLAMIC, LAW)  
7        (@, newton.apple.com)          (VNEWS, 1.41)  
8                 (sandvik, @)         (Los, Angeles)  
9         (@, zoo.toronto.edu)        (M/S, 525-3684)  
10        (@, cco.caltech.edu)    (Frequently, Asked)  
11       (@, access.digex.com)         (Beam, Jockey)  
12            (Henry, Spencer)      (sank, Manhattan)  
13             (@, netcom.com)          (fait, comme)  
14              (Jon, Livesey)     (Allan, Schneider)  
15                  (keith, @)       (Henry, Spencer)  
16                (livesey, @)          (Ron, Baalke)  
17                    (TIN, [)      (Tourist, Bureau)  
18                     (ra, >)      (Jet, Propulsion)  
19                  (henry, @)        (Bake, Timmons)

#### Justification to consider overlap of techniques

> c. How much overlap is there among the techniques? Do you think it makes sense to consider
the union of the results?


* Chi-Sq test, PMI - gives probability lift or term frequency
* Frequency with filter and T-test gives frequency of occurence
* By analysing and comparing all the tabular results, it seems like results of frequency with filter and T-test with filter is almost similar while PMI results is similar to Chi-Sq test. 
* On strict comparision we can see that PMI and Chi-Sq has better results (ie..alphabetic variables) without even applying filters. 
* But Chi-Sq test and PMI results give relationship between two variables but not strength or size of the relationship. 
* So, in my perspective if we consider union of term frequency (probability lift) and frequency of occurency, we get better results  as both size and relationship of variables will be taken into account instead of combining all the four techniques which might give inconsistent results. 
* In other words, we should either combine PMI and frequency with filter or PMI and T-test or Chi-Sq and frequency with filter or Chi-Sq and T-test for better results.

**References**:
1. https://medium.com/@nicharuch/collocations-identifying-phrases-that-act-like-individual-wordsin-nlp-f58a93a2f84ab
2. https://bib.irb.hr/datoteka/251298.110-4-157-203.pdf
3. http://www.site.uottawa.ca/~diana/csi5180/L7.pdf

#### Q2. SVM and NB for Text Classification (75 marks)

> a. Clean the text: ( 10 marks )
 * Remove stop words
 * Remove numbers and other non-letter characters
 * Stem the words

> Tokenizing the given dataset of documents
* We are converting the dataset into array of documents instead of single array of words as Tf-Idf calculates score relative to each document.
*  We need to find bag of words as part of feature extraction, so first need to remove unimportant tokens in the documents and clean the dataset.
* To identify stopwords, which are of lowercase in NLTK library, we need to convert all words of document to lowercase and then try to remove them.



  

In [25]:
#Tokeinze the documents
newsgroups = newsgroups_train.data
tokenizedWords=[]*len(newsgroups)
for i in range(len(newsgroups)):
    tokenizedWords.append(word_tokenize(newsgroups[i]))

In [26]:
#Converting all into lower case words before removing stop words
for i in range(len(tokenizedWords)):
    for j in range(len(tokenizedWords[i])):
        tokenizedWords[i][j] = tokenizedWords[i][j].lower()

In [27]:
#Remove Stop words
#Get all stop words from NLTK
#Ref: https://www.geeksforgeeks.org/removing-stop-words-nltk-python/
stop_words = set(stopwords.words('english')) 

for i in range(len(tokenizedWords)):
    for j in range(len(tokenizedWords[i])):
        tokenizedWords[i] = [w for w in tokenizedWords[i] if not w in stop_words]

In [28]:
#Remove numbers and other non-letter characters
for i in range(len(tokenizedWords)):
    for j in range(len(tokenizedWords[i])):
        tokenizedWords[i] = [w for w in tokenizedWords[i] if w.isalpha()]

In [29]:
#Stem the words
#Ref: Lab Text Processing
from nltk.stem import PorterStemmer

ps = PorterStemmer()

for i in range(len(tokenizedWords)):
    for j in range(len(tokenizedWords[i])):
        tokenizedWords[i][j] = ps.stem(tokenizedWords[i][j])

In [31]:
#Converting back the cleaned tokens into to String i.e, documents 
#Ref: https://www.decalage.info/en/python/print_list
cleanedDocuments = [] 
for i in range(len(tokenizedWords)):
        joinedString  = ' '.join(tokenizedWords[i])
        cleanedDocuments.append(joinedString)

In [74]:
#Sample cleaned Documemnt without Stop words, numbers and other non-letter characters and stemming done.
print(cleanedDocuments[1])

subject biblic back koresh tape cite enclos kmcvay ken mcvay organ old frog almanac line articl stephen write seem koresh yet anoth messeng got kill messag carri say noth seem bar evid contrari koresh simpli anoth derang fanat thought neccessari take whole bunch folk children satisfi delusion mania jim jone circa mean time sure learn lot evil corrupt surpris thing gotten rotten nope fruitcak like koresh demonstr evil corrupt centuri old frog almanac salut old frog hiss f ryugen fisher sco xenix gt ladysmith british columbia canada serv central vancouv island public access usenet internet mail home holocaust almanac


#### Tf-Idf (Term Frequency- Inverse Document Frequency)weighted vector representation
> b. Study the section on feature extraction in Scikit Learn,  and convert the corpus into a bag-of-words tf-idf weighted vector representation

Ref: https://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction
 
>  Two methods to  perform feature extraction from text files
* Count Vectorizer + Tf-IDF Transformer
* Tf-IDF Vectorizer

Ref: http://kavita-ganesan.com/tfidftransformer-tfidfvectorizer-usage-differences/#.XS8mEuhKjIU
Ref: https://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction

##### Count Vectorizer + Tf-IDF Transformer

> Count Vectroiser is used to determine the feartures i.e, the bag of words for each document in the corpus and then find the counts of each word in the document. As documents may have huge number of words which results in a massive matirx. Count Vectoriser uses sparse representation of the matrix, which reduces the overhead in representing it in a massive matrix.

In [75]:
#Count Vectorizing
#Ref: Lab
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(cleanedDocuments)
X_train_counts.shape

(2034, 18399)

> TF-IDF Transformer computes IDF values for the array of documents in the dataset
IDF values calculates the score for each word(term) based on their appearance in each to every document in our collection,thereby normalises the importance of tokens in the document( ie.., balance the dataset as unimportant tokens with high term frequency might grade down the important tokens term frequency)

In [33]:
#TfidfTransformer 
#Ref: Lab
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X_train_tfidf.shape

(2034, 18399)

> Displaying the TF_IDF scores for the first document :
* The more common the word across documents, the lower its score and the more unique a word is to our first document the higher the score

In [34]:
feature_names = count_vect.get_feature_names()
 
#tfidf values for first document
first_document_vector=X_train_tfidf[0]
 
#print the scores
df = pd.DataFrame(first_document_vector.T.todense(), index=feature_names, columns=["tfidf"])
df.sort_values(by=["tfidf"],ascending=False)

tfidf
rych          0.457032
file          0.382339
textur        0.337113
save          0.234388
hawk          0.232725
rule          0.226992
format        0.157913
rychard       0.152344
restart       0.152344
posit         0.142184
reload        0.139020
edinburgh     0.139020
inform        0.126502
preserv       0.111206
default       0.110107
manual        0.105395
psycholog     0.103792
anyon         0.103063
explicitli    0.102313
store         0.100939
tel           0.096783
orient        0.094283
univ          0.093819
virtual       0.093819
plane         0.092493
notic         0.087949
environ       0.087615
somewher      0.087286
map           0.087286
laboratori    0.079820
...                ...
gall          0.000000
galilleo      0.000000
galileo       0.000000
galilean      0.000000
galbraith     0.000000
garden        0.000000
galaxi        0.000000
galatian      0.000000
galahad       0.000000
galacticentr  0.000000
galact        0.000000
gal           0.000000
galleri       0.000000
gallileo      0.000000
gambit        0.000000
game          0.000000
gamepro       0.000000
gamma         0.000000
ganador       0.000000
gandalf       0.000000
gandhi        0.000000
gang          0.000000
ganymed       0.000000
gao           0.000000
gap           0.000000
gara          0.000000
garbag        0.000000
garch         0.000000
garcia        0.000000
ºnd           0.000000

[18399 rows x 1 columns]

#### TF-IDF Vectorizer

> In TF-IDF Vectorizer all the steps done as part of CountVectorizer and TF-IDF transformer is done in a single step (ie.., both term frequency and normalisation of tokens in document)

In [35]:
#Using TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(cleanedDocuments)
#print(vectorizer.get_feature_names())
print(X.shape)


(2034, 18399)


> Printing the first document TF_IDF values calculated using TF_IDF vectorizer
* We can observe the values are same as the values calculated using CountVectorizer+TF-IDF Transformer. So, we can use any one of them based on the requirements.

In [36]:
 #first document TF_IDF values
first_vector_tfidfvectorizer=X[0]
 
# Print the values
df = pd.DataFrame(first_vector_tfidfvectorizer.T.todense(), index=vectorizer.get_feature_names(), columns=["tfidf"])
df.sort_values(by=["tfidf"],ascending=False)

tfidf
rych          0.457032
file          0.382339
textur        0.337113
save          0.234388
hawk          0.232725
rule          0.226992
format        0.157913
rychard       0.152344
restart       0.152344
posit         0.142184
reload        0.139020
edinburgh     0.139020
inform        0.126502
preserv       0.111206
default       0.110107
manual        0.105395
psycholog     0.103792
anyon         0.103063
explicitli    0.102313
store         0.100939
tel           0.096783
orient        0.094283
univ          0.093819
virtual       0.093819
plane         0.092493
notic         0.087949
environ       0.087615
somewher      0.087286
map           0.087286
laboratori    0.079820
...                ...
gall          0.000000
galilleo      0.000000
galileo       0.000000
galilean      0.000000
galbraith     0.000000
garden        0.000000
galaxi        0.000000
galatian      0.000000
galahad       0.000000
galacticentr  0.000000
galact        0.000000
gal           0.000000
galleri       0.000000
gallileo      0.000000
gambit        0.000000
game          0.000000
gamepro       0.000000
gamma         0.000000
ganador       0.000000
gandalf       0.000000
gandhi        0.000000
gang          0.000000
ganymed       0.000000
gao           0.000000
gap           0.000000
gara          0.000000
garbag        0.000000
garch         0.000000
garcia        0.000000
ºnd           0.000000

[18399 rows x 1 columns]

#### Tfidftransformer vs. Tfidfvectorizer
Ref: http://kavita-ganesan.com/tfidftransformer-tfidfvectorizer-usage-differences/#.XS8mEuhKjIU


> * TF-IDF tranformer is systematic stepwise process, as it starts with Countvectorizer which does tokenisation, removal of stopwords internally and then transformer normalises the tokens by calculating inverse document frequency.
* Tf-IDf Vectorizer does everything together (word counts, IDF values, and Tf-idf scores)
* If we focus on calculating term frequency better to use TF-IDF transformer or if the focus is calculating TF_IDF values then TF_IDF vectorizes serves the purpose in easier way.

#### c. Split the data randomly into training and testing set (70-30 %). ( 5 marks )
* Training the classifier using training data
* Calculate performance of classifier with the help of test data
* Report Confusion matrix

In [38]:
#Spliting Test-Train classification of dataset
from sklearn.model_selection import train_test_split
train_X,test_X,train_Y,test_Y=train_test_split(X,newsgroups_train.target,test_size=0.3)

#### Train Multinomial NB and report confusion matrix.

In [43]:
#feeding training data to model
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

clf = MultinomialNB().fit(train_X, train_Y)
# performance test of classifier using test data
predicted = clf.predict(test_X)

In [44]:
# Accuracy and Confusion Matrix
import numpy as np
print("Accuracy Score :",accuracy_score(predicted, test_Y)*100)
print("Confusion Matrix :")
print(confusion_matrix(test_Y, predicted))

Accuracy Score : 86.41571194762683
Confusion Matrix :
[[132   1   1   0]
 [  0 168   2   0]
 [  0   0 174   0]
 [ 64   2  13  54]]


#### Train SVM and report confusion matrix
> kernel types:
* Linear
* Poly
* RBF (Radial Basis Function)
* Sigmoid

Ref: https://medium.com/@bedigunjit/simple-guide-to-text-classification-nlp-using-svm-and-naive-bayes-with-python-421db3a72d34


> #### Kernel - Linear

In [45]:
from sklearn import svm
SVM = svm.SVC(C=1.0, kernel='linear', degree=3, gamma=2)
SVM.fit(train_X, train_Y)
# predict the labels on validation dataset
predictions_SVM = SVM.predict(test_X)
# Use accuracy_score function to get the accuracy
print("Accuracy Score :",accuracy_score(predictions_SVM, test_Y)*100)
print("Confusion Matrix :")
print(confusion_matrix(test_Y, predictions_SVM))

Accuracy Score : 95.5810147299509
Confusion Matrix :
[[129   1   1   3]
 [  0 170   0   0]
 [  0   5 168   1]
 [  9   5   2 117]]


> #### Kernel - Poly

In [46]:
SVMpoly = svm.SVC(C=1.0, kernel='poly', degree=3, gamma=2)
SVMpoly.fit(train_X, train_Y)
# predict the labels on validation dataset
predictions_poly = SVMpoly.predict(test_X)
print("Accuracy Score :",accuracy_score(predictions_poly, test_Y)*100)
print("Confusion Matrix :")
print(confusion_matrix(test_Y, predictions_poly))

Accuracy Score : 77.74140752864157
Confusion Matrix :
[[103  27   1   3]
 [  0 170   0   0]
 [  0  19 155   0]
 [  9  77   0  47]]


> #### Kernel - rbf

In [47]:
SVM = svm.SVC(C=1.0, kernel='rbf', degree=3, gamma=2)
SVM.fit(train_X, train_Y)
# predict the labels on validation dataset
predictions_rbf = SVM.predict(test_X)
# Use accuracy_score function to get the accuracy
predictions_poly = SVMpoly.predict(test_X)
print("Accuracy Score :",accuracy_score(predictions_rbf, test_Y)*100)
print("Confusion Matrix :")
print(confusion_matrix(test_Y, predictions_rbf))

Accuracy Score : 88.21603927986907
Confusion Matrix :
[[124   4   3   3]
 [  0 170   0   0]
 [  0   5 169   0]
 [ 17  27  13  76]]


> #### Kernel - Sigmoid

In [48]:
SVM = svm.SVC(C=1.0, kernel='sigmoid', degree=3, gamma=2)
SVM.fit(train_X, train_Y)
# predict the labels on validation dataset
predictions_sig = SVM.predict(test_X)
# Use accuracy_score function to get the accuracy
predictions_poly = SVMpoly.predict(test_X)
print("Accuracy Score :",accuracy_score(predictions_sig, test_Y)*100)
print("Confusion Matrix :")
print(confusion_matrix(test_Y, predictions_sig))

Accuracy Score : 95.5810147299509
Confusion Matrix :
[[129   1   1   3]
 [  0 170   0   0]
 [  1   6 167   0]
 [ 10   3   2 118]]


#### Which algorithm has higher accuracy and why?

> References: 
1. https://pdfs.semanticscholar.org/55c5/9874114617b57eedd8636c5d0e7785fb885f.pdf
2. https://stackoverflow.com/questions/35360081/naive-bayes-vs-svm-for-classifying-text-data
3. https://stats.stackexchange.com/questions/136538/is-the-naive-bayes-family-of-classifiers-linear

> From our observation and datset, SVM  is performing better than Multinomial NB. But, the results clearly depends on the usage of dataset, cleaning, tuning parameters.
* NB is generally stated as linear classifier (by not taking account of special cases). So, if datset has non-linearly separable data or noisy data, NB performs poor results compared to SVM. In theory, SVM  maps and represents data in higher dimensional hyperplans to perform better results even though dataset consists of non-linear data or noise.
* In NB, featured are treated independently, whereas SVM gives importance to the relation between features
* So, if the focus is on features and their interaction or if the dataset consists of little bit of noise and non-linear seperable data then SVM gives better results

#### Does changing the kernel of the SVM change the accuracy or decrease confusion between classes?

> Ref: 
1. https://www.quora.com/When-can-I-use-Linear-SVM-instead-of-RBF-polynomial-or-a-sigmoid-kernel
2. https://pdfs.semanticscholar.org/55c5/9874114617b57eedd8636c5d0e7785fb885f.pdf
3. https://www.kdnuggets.com/2016/06/select-support-vector-machine-kernels.html

> Yes. Kernel plays a major role in the results. So, choosing proper kernel function is much needed in SVM and it depends on the type of dataset we are working.
Here in our dataset, as we cleaned and removed the noise Linear kernel performed better. As Linear performed we can assume the dataset is not having much non-linearly seperable samples.
* Linear: Suitable if datset is properly tuned, having large number of features without noise, and if there is no necessity of mapping features in high dimensional space (ie.. no non linear data in the datset)
* Non-Linear:
   * Polynomial: Similar to linear with arbitary boundaries. Suitable for non-linear data mapping without noise in the datset.
   * RBF: More Suitable for dataset having less number of features and even though the datset has attributes in non-linear manner unlike linear kernel or multinomial NB. It is the best kernel of SVM and  serves the purpose which cannot be done by other kernels or ordinary NB. But, if the dataset is large it is expensive and complex to implement.
   * Sigmoid: It is generally used in Neural networks and still in research phase which 
* Based on the complexity of dataset,expenses, noise, non- linear data in dataset we should choose the kernel types.


#### Perform part-of-speech tagging on the raw data (i.e. prior to cleaning it),

In [49]:
from sklearn.datasets import fetch_20newsgroups
interest = ['alt.atheism', 'talk.religion.misc','comp.graphics','sci.space',]
newsgroups_raw = fetch_20newsgroups(subset='train',categories=interest,shuffle=True, random_state=42)

> #### Tokenizing Raw data for POS tagging

In [50]:
#Tokenizing Raw data for POS tagging
import nltk
import pandas as pd
from nltk import pos_tag
from nltk.tokenize import word_tokenize, sent_tokenize
rawWords=[]*len(newsgroups_raw.data)
for i in range(len(newsgroups_raw.data)):
    rawWords.append(word_tokenize(newsgroups_raw.data[i]))

> #### POS tagging on raw data

In [51]:
#POS tagging on raw data before cleaning
for i in range(len(rawWords)):
        rawWords[i]=nltk.pos_tag(rawWords[i])

#### clean as in part (a) above, and extract the nouns only to obtain a bag-of-words tf-idf weighted vector representation using only the nouns

> Ref: https://stackoverflow.com/questions/40167612/how-to-keep-only-the-noun-words-in-a-wordlist-python-nltk

* Extracting Nouns from the raw data and storing them as array of arrays of documents
* Cleaning
   * Remove stop words
   * Remove numbers and other non-letter characters
   * Stem the words 
* Feature Extraction using TF-IDF  Vectorizer
* Split Extracted Noun dataset into test-train
* Train the classifiers NB, SVM and report Confusion Matrices for same

   

In [52]:
#Extracting Nouns from the raw data

ExtractedNouns = []*len(rawWords)

for i in range(len(rawWords)):
   ExtractedNouns.append([word for word,pos in rawWords[i] if (pos in ['NN','NNP','NNS','NNPS'])])

In [53]:
#Converting all into lower case words before removing stop words
for i in range(len(ExtractedNouns)):
    for j in range(len(ExtractedNouns[i])):
        ExtractedNouns[i][j] = ExtractedNouns[i][j].lower()

In [54]:
#Remove Stop words
#Get all stop words from NLTK
#Ref: https://www.geeksforgeeks.org/removing-stop-words-nltk-python/
stop_words = set(stopwords.words('english')) 

for i in range(len(ExtractedNouns)):
        ExtractedNouns[i] = [w for w in ExtractedNouns[i] if not w in stop_words]

In [55]:
#Remove numbers and other non-letter characters
for i in range(len(ExtractedNouns)):
        ExtractedNouns[i] = [w for w in ExtractedNouns[i] if w.isalpha()]

In [56]:
#Stem the words
#Ref: Lab Text Processing
from nltk.stem import PorterStemmer

ps = PorterStemmer()

for i in range(len(ExtractedNouns)):
    for j in range(len(ExtractedNouns[i])):
        ExtractedNouns[i][j] = ps.stem(ExtractedNouns[i][j])

In [57]:
#Converting back to String
#Ref: https://www.decalage.info/en/python/print_list
cleanedNouns = [] 

for i in range(len(tokenizedWords)):
        joinedString  = ' '.join(ExtractedNouns[i])
        cleanedNouns.append(joinedString)

In [58]:
#Using TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer_Nouns = TfidfVectorizer()
X_Nouns = vectorizer_Nouns.fit_transform(cleanedNouns)
#print(vectorizer.get_feature_names())
print(X_Nouns.shape)

(2034, 15279)


In [59]:
 #first document TF_IDF values
first_vector_tfidfvectorizer=X_Nouns[0]
 
# Print the values
df = pd.DataFrame(first_vector_tfidfvectorizer.T.todense(), index=vectorizer_Nouns.get_feature_names(), columns=["tfidf"])
df.sort_values(by=["tfidf"],ascending=False)

tfidf
rych            0.503316
file            0.430910
textur          0.375352
hawk            0.263366
rule            0.255505
format          0.176297
rychard         0.167772
edinburgh       0.153098
inform          0.142292
psycholog       0.128147
virtual         0.125117
default         0.122468
anyon           0.114062
orient          0.111161
tel             0.107180
univ            0.103320
plane           0.102336
map             0.100494
environ         0.096487
model           0.089417
laboratori      0.087904
dept            0.086952
fax             0.085820
hi              0.085820
email           0.084537
posit           0.082938
noth            0.070927
line            0.022269
subject         0.022171
petrich         0.000000
...                  ...
fwi             0.000000
fwhm            0.000000
fwd             0.000000
fw              0.000000
fullview        0.000000
fume            0.000000
fun             0.000000
function        0.000000
fund            0.000000
fundament       0.000000
fundamentalist  0.000000
fundi           0.000000
fundrais        0.000000
fung            0.000000
funk            0.000000
funni           0.000000
furnish         0.000000
furrow          0.000000
furthermor      0.000000
furusawa        0.000000
fuse            0.000000
fuselag         0.000000
fusion          0.000000
fuss            0.000000
fussr           0.000000
futher          0.000000
futur           0.000000
fuzzi           0.000000
fv              0.000000
ªl              0.000000

[15279 rows x 1 columns]

In [60]:
#Split Noun data as Test and Train
from sklearn.model_selection import train_test_split
train_X_Nouns,test_X_Nouns,train_Y_Nouns,test_Y_Nouns=train_test_split(X_Nouns,newsgroups_train.target,test_size=0.3)

In [61]:
# Train Multinomial NB and report confusion matrix.
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

clf = MultinomialNB().fit(train_X_Nouns, train_Y_Nouns)
predictedNouns = clf.predict(test_X_Nouns)

In [62]:
print("Accuracy Score :",accuracy_score(predictedNouns, test_Y_Nouns)*100)
print("Confusion Matrix :")
print(confusion_matrix(test_Y_Nouns, predictedNouns))

Accuracy Score : 91.65302782324059
Confusion Matrix :
[[135   0   1   0]
 [  0 177   4   0]
 [  0   4 184   0]
 [ 37   2   3  64]]


In [63]:
#Train SVM and report confusion matrix.
from sklearn import svm

SVMNouns = svm.SVC(C=1.0, kernel='linear', degree=3, gamma='auto')
SVMNouns.fit(train_X_Nouns, train_Y_Nouns)
# predict the labels on validation dataset
predictions_SVM_Nouns = SVMNouns.predict(test_X_Nouns)
# Use accuracy_score function to get the accuracy
print("Accuracy Score :",accuracy_score(predictions_SVM_Nouns, test_Y_Nouns)*100)
print("Confusion Matrix :")
print(confusion_matrix(test_Y_Nouns, predictions_SVM_Nouns))

Accuracy Score : 94.92635024549918
Confusion Matrix :
[[126   0   1   9]
 [  0 181   0   0]
 [  0   8 178   2]
 [  9   2   0  95]]


####  How does this accuracy compare with that of part(c)?

Ref: https://www.quora.com/Which-algorithm-is-better-for-implementing-to-get-high-accuracy-in-analysis-Naive-Bayes-or-a-support-vector-machine-SVM


> There is not much difference in accuracy results of SVM by extracting nouns while compared to previous one .The slight decrease in accuracy compared to the previous one might be due to  slightly less number of large features, as only extracted nouns is taken into account to obtain bag of words. But there is huge difference in accuracy results for NB,this might be because by properly extracting bag of words in general NB performs pretty well for smaller datasets compared to SVM. SVM is more suitable for complex large datsets. Here we extracted only nouns (proper without noise) and calculated TF-IDF values, which increased slightly might be other reason for the increase in NB accuracy.

#### How does the size of the vocabulary compare with that of part (c)?

As shown below the vocabulary got decreased after noun extraction

In [64]:
#Vocabulary after noun extraction 
print("Vocabulary after noun extraction")
print (len(vectorizer_Nouns.vocabulary_))

Vocabulary after noun extraction
15279


In [65]:
#Vocabuylary before noun extraction
print("Vocabuylary before noun extraction")
print (len(vectorizer.vocabulary_))

Vocabuylary before noun extraction
18399
